#pragma checksum "..\..\..\DynamicIsland\MainWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "D589F3233272076EF12F005A86E4EC141933F528"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DynamicIsland.UI;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DynamicIsland {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 32 "..\..\..\DynamicIsland\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RootGrid;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\DynamicIsland\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border MainSurface;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\DynamicIsland\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.SolidColorBrush MainSurfaceBackgroundBrush;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\DynamicIsland\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.SolidColorBrush MainSurfaceBorderBrush;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\DynamicIsland\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform IslandScaleTransform;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\DynamicIsland\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid StatusCard;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\..\DynamicIsland\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.TranslateTransform StatusContentTranslateTransform;
        
        #line default
        #line hidden
        
        
        #line 91 "..\..\..\DynamicIsland\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border GlyphContainer;
        
        #line default
        #line hidden
        
        
        #line 100 "..\..\..\DynamicIsland\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.SolidColorBrush GlyphBorderBrush;
        
        #line default
        #line hidden
        
        
        #line 104 "..\..\..\DynamicIsland\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse StatusAccentEllipse;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\DynamicIsland\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.SolidColorBrush StatusAccentEllipseBrush;
        
        #line default
        #line hidden
        
        
        #line 123 "..\..\..\DynamicIsland\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel StatusTextPanel;
        
        #line default
        #line hidden
        
        
        #line 127 "..\..\..\DynamicIsland\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StatusTitleText;
        
        #line default
        #line hidden
        
        
        #line 140 "..\..\..\DynamicIsland\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid ExpandedRegion;
        
        #line default
        #line hidden
        
        
        #line 146 "..\..\..\DynamicIsland\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.TranslateTransform ExpandedRegionTranslateTransform;
        
        #line default
        #line hidden
        
        
        #line 151 "..\..\..\DynamicIsland\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid ActionPanel;
        
        #line default
        #line hidden
        
        
        #line 164 "..\..\..\DynamicIsland\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel ActionPanelHeader;
        
        #line default
        #line hidden
        
        
        #line 178 "..\..\..\DynamicIsland\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.UniformGrid ActionButtonsPanel;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.5.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DynamicIsland;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\DynamicIsland\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.5.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.RootGrid = ((System.Windows.Controls.Grid)(target));
            
            #line 34 "..\..\..\DynamicIsland\MainWindow.xaml"
            this.RootGrid.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.RootGrid_OnMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.MainSurface = ((System.Windows.Controls.Border)(target));
            
            #line 44 "..\..\..\DynamicIsland\MainWindow.xaml"
            this.MainSurface.MouseEnter += new System.Windows.Input.MouseEventHandler(this.MainSurface_OnMouseEnter);
            
            #line default
            #line hidden
            
            #line 45 "..\..\..\DynamicIsland\MainWindow.xaml"
            this.MainSurface.MouseLeave += new System.Windows.Input.MouseEventHandler(this.MainSurface_OnMouseLeave);
            
            #line default
            #line hidden
            return;
            case 3:
            this.MainSurfaceBackgroundBrush = ((System.Windows.Media.SolidColorBrush)(target));
            return;
            case 4:
            this.MainSurfaceBorderBrush = ((System.Windows.Media.SolidColorBrush)(target));
            return;
            case 5:
            this.IslandScaleTransform = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 6:
            this.StatusCard = ((System.Windows.Controls.Grid)(target));
            
            #line 80 "..\..\..\DynamicIsland\MainWindow.xaml"
            this.StatusCard.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.StatusCard_OnMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 7:
            this.StatusContentTranslateTransform = ((System.Windows.Media.TranslateTransform)(target));
            return;
            case 8:
            this.GlyphContainer = ((System.Windows.Controls.Border)(target));
            return;
            case 9:
            this.GlyphBorderBrush = ((System.Windows.Media.SolidColorBrush)(target));
            return;
            case 10:
            this.StatusAccentEllipse = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 11:
            this.StatusAccentEllipseBrush = ((System.Windows.Media.SolidColorBrush)(target));
            return;
            case 12:
            this.StatusTextPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 13:
            this.StatusTitleText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            this.ExpandedRegion = ((System.Windows.Controls.Grid)(target));
            return;
            case 15:
            this.ExpandedRegionTranslateTransform = ((System.Windows.Media.TranslateTransform)(target));
            return;
            case 16:
            this.ActionPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 17:
            this.ActionPanelHeader = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 18:
            this.ActionButtonsPanel = ((System.Windows.Controls.Primitives.UniformGrid)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

